version: "2"
services:

## CAPES Databases ##

  etherpad-mysql:
    container_name: capes-etherpad-mysql
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: etherpad
      MYSQL_USER: etherpad
      MYSQL_PASSWORD: etherpad_mysql_passphrase
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - /var/lib/docker/volumes/mysql/etherpad/_data:/var/lib/mysql:z

  gitea-mysql:
    container_name: capes-gitea-mysql
    restart: unless-stopped
    image: mysql:5.7
    volumes:
      - /var/lib/docker/volumes/mysql/gitea/_data:/var/lib/mysql:z
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea_mysql_passphrase

  elasticsearch:
    container_name: capes-thehive-elasticsearch
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /var/lib/docker/volumes/elasticsearch/_data:/usr/share/elasticsearch/data:z

  rocketchat-mongo:
    container_name: capes-rocketchat-mongo
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - /var/lib/docker/volumes/rocketchat/_data:/data/db:z
      - /var/lib/docker/volumes/rocketchat/dump/_data:/dump:z
    command: mongod --smallfiles

## CAPES Services ##

  landing_page:
    container_name: capes-landing_page
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./landing_page:/usr/share/nginx/html:z
    ports:
      - "80:80"

  portainer:
    container_name: capes-portainer
    restart: unless-stopped
    image: portainer/portainer:latest
    volumes:
      - /var/lib/docker/volumes/portainer/_data:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2000:9000"

  cyberchef:
    container_name: capes-cyberchef
    restart: unless-stopped
    image: mpepping/cyberchef:latest
    ports:
      - "8000:8000"

  gitea:
    container_name: capes-gitea
    restart: unless-stopped
    image: gitea/gitea:latest
    volumes:
      - /var/lib/docker/volumes/gitea/_data:/data:z
    ports:
      - "2222:22"
      - "4000:3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=capes-gitea

  etherpad:
    container_name: capes-etherpad
    restart: unless-stopped
    image: tvelocity/etherpad-lite
    ports:
      - "0.0.0.0:5000:9001"
    environment:
      - ETHERPAD_TITLE=CAPES
      - ETHERPAD_PORT=9001
      - ETHERPAD_ADMIN_PASSWORD=etherpad_admin_passphrase
      - ETHERPAD_ADMIN_USER=admin
      - ETHERPAD_DB_TYPE=mysql
      - ETHERPAD_DB_HOST=etherpad-mysql
      - ETHERPAD_DB_USER=etherpad
      - ETHERPAD_DB_PASSWORD=etherpad_mysql_passphrase
      - ETHERPAD_DB_NAME=etherpad
    depends_on:
      - etherpad-mysql

  thehive:
    container_name: capes-thehive
    restart: unless-stopped
    image: thehiveproject/thehive:latest
    environment:
      - CORTEX_URL=capes-cortex
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"

  cortex:
    container_name: capes-cortex
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"

  rocketchat:
    container_name: capes-rocketchat
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://rocketchat-mongo:27017/rocketchat
      - ROOT_URL=http://localhost:3000
      - Accounts_UseDNSDomainCheck=True
    depends_on:
      - rocketchat-mongo
    ports:
      - "3000:3000"

  mumble:
    image: phlak/mumble:latest
    container_name: capes-mumble
    restart: unless-stopped
    ports:
      - "64738:64738"
    volumes:
      - mumble-data:/etc/mumble:z

volumes:
  mumble-data:
