heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://capes-elasticsearch-1:9200
    - http://capes-elasticsearch-2:9200
    - http://capes-elasticsearch-3:9200
    - http://capes-kibana:5601
    - http://capes-thehive-elasticsearch:9200
    - http://capes-portainer:9000
    - https://capes-landing-page:443
    - http://capes-cyberchef:8000
    - http://capes-gitea:3000
    - http://capes-etherpad:9001
    - http://capes-thehive:9000
    - http://capes-cortex:9001
    - http://capes-rocketchat:3000
  ssl.verification_mode: none

- type: icmp
  schedule: '@every 5s'
  hosts:
    - capes-mumble
    - capes-heartbeat
    - capes-metricbeat
    - capes-etherpad-mysql
    - capes-gitea-mysql
    - capes-rocketchat-mongo

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:capes-elasticsearch-1:9200}'
